### ISSUE TITLE
Simple Try to pausing reading

### ISSUE THREAD

**Issue by ludwich66** [KrystianD/pyrc3563#2]
Hi Krystian,
i do the simple Test to modify your Cod to Pause readings for 5 seconds.
I see with this methode reading is not actuall after change object (Resistor).
Do i stop Programm and restart it is a correct Measurement.

My Plan:
I wanted to delay the measurement to change the measurement object (from cell to cell).
These values ​​should then be written to a file log. (time,cell,V,R)

Can you tell me how (where) I should put a break?

Ludwich

```
from rc3563 import *
import time
# import argparse
preset_port = "COM5" # '/dev/ttyUSB0'

def main():
    #argparser = argparse.ArgumentParser(prog="python -m cli")
    #argparser.add_argument("path", help="Serial port path")
    #args = argparser.parse_args()
    rc = RC3563(preset_port)
    while True:
        pkt = rc.read()
        time.sleep(5.5) # Pause 5,5 sec
        print(f"V: {pkt.voltage_v:.3f}, R: {pkt.resistance_ohm:.6f}")
        
main()
```

**Comment by KrystianD** [comment]
@ludwich66 you need to read all packets, otherwise they would queue up. Just use the reading every now and then. Introduce `last_time` variable and check when last usage was, if more than 5.5s ago, use it again, but read all packets.
